version: '3'
services:
  my-app:
    image: my-tomcat-app:latest
    ports:
      - "8080:8080"

  postgres:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dbCleverBank